"""
Alert models for AegisForge platform.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, ConfigDict

from .base import BaseEvent, EventMetadata, EventSeverity
from .security_events import SecurityEvent


class AlertStatus(str, Enum):
    """Alert lifecycle status."""
    OPEN = "open"
    INVESTIGATING = "investigating"
    ACKNOWLEDGED = "acknowledged"
    FALSE_POSITIVE = "false_positive"
    CLOSED = "closed"
    SUPPRESSED = "suppressed"


class AlertEvidence(BaseModel):
    """Evidence supporting an alert."""
    model_config = ConfigDict(extra="allow")
    
    evidence_id: str
    evidence_type: str  # log, metric, trace, artifact, network_capture
    source: str
    description: str
    data: Dict[str, any] = Field(default_factory=dict)
    timestamp: datetime
    hash_sha256: Optional[str] = None
    size_bytes: Optional[int] = None
    minio_bucket: Optional[str] = None
    minio_object: Optional[str] = None


class Alert(BaseEvent):
    """Security alert generated by detection engine."""
    model_config = ConfigDict(extra="allow")
    
    alert_id: UUID = Field(default_factory=uuid4)
    rule_id: Optional[str] = None
    rule_name: Optional[str] = None
    rule_version: Optional[int] = None
    
    # Alert classification
    title: str
    description: str
    severity: EventSeverity
    confidence: float = Field(ge=0.0, le=1.0)
    
    # MITRE ATT&CK mapping
    mitre_techniques: List[str] = Field(default_factory=list)
    mitre_tactics: List[str] = Field(default_factory=list)
    
    # Affected assets
    affected_asset_ids: List[str] = Field(default_factory=list)
    affected_namespaces: List[str] = Field(default_factory=list)
    affected_pods: List[str] = Field(default_factory=list)
    affected_nodes: List[str] = Field(default_factory=list)
    
    # Evidence
    evidence: List[AlertEvidence] = Field(default_factory=list)
    evidence_count: int = 0
    
    # Correlation
    correlated_alert_ids: List[str] = Field(default_factory=list)
    correlation_rule_id: Optional[str] = None
    event_count: int = 1
    
    # Status and assignment
    status: AlertStatus = AlertStatus.OPEN
    assignee: Optional[str] = None
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None
    closed_at: Optional[datetime] = None
    closed_by: Optional[str] = None
    close_reason: Optional[str] = None
    
    # MITRE ATT&CK enrichment
    mitre_technique_details: Dict[str, Dict[str, any]] = Field(default_factory=dict)
    
    # Recommended actions
    recommended_actions: List[str] = Field(default_factory=list)
    recommended_runbooks: List[str] = Field(default_factory=list)
    
    # Timeline
    first_seen: datetime = Field(default_factory=datetime.utcnow)
    last_seen: datetime = Field(default_factory=datetime.utcnow)
    
    # Suppression
    suppression_rule_id: Optional[str] = None
    suppressed_until: Optional[datetime] = None
    
    # AI enrichment
    ai_summary: Optional[str] = None
    ai_triage: Optional[Dict[str, any]] = None
    ai_confidence: Optional[float] = None


class AlertSummary(BaseModel):
    """Summary view of alert for listings."""
    model_config = ConfigDict(extra="allow")
    
    alert_id: UUID
    rule_id: Optional[str]
    rule_name: Optional[str]
    title: str
    severity: EventSeverity
    confidence: float
    status: AlertStatus
    affected_asset_count: int
    first_seen: datetime
    last_seen: datetime
    assignee: Optional[str]
    mitre_techniques: List[str] = Field(default_factory=list)